apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: forge
