apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        workloadIdentity:
          clusterLocation: ${GKE_LOCATION}
          clusterName: ${GKE_CLUSTER_NAME}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
