apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: forge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - { name: otlp-http, port: {{ .Values.service.port }}, targetPort: otlp-http }
    - { name: otlp-grpc, port: {{ .Values.service.grpcPort }}, targetPort: otlp-grpc }
    - { name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics }
